package tachiyomi.core.common.util.lang

/**
 * Japanese shinjitai -> kyujitai pairs, so that a title written in either form is reachable
 * from a query written in the other.
 *
 * The mapping is deliberately new -> old: [tachiyomi.core.common.util.lang.SearchTextNormalizer] applies it *before*
 * the traditional -> simplified table, so both sides of a pair fall through to the same
 * simplified character (桜 -> 櫻 -> 樱, and 櫻 -> 樱 directly). Mapping straight to simplified
 * here would leave 桜 stranded, because neither zhconv nor OpenCC knows the Japanese forms.
 *
 * Covers the joyo and jinmeiyo lists, their variants, and the common hyogai forms.
 * Source: Wikipedia "Kyujitai". Generated by script; do not edit by hand.
 */
internal object SearchJapaneseVariants {

    private const val SHINJITAI = "" +
        "両並乗亀予亜仏仮伝併価倹偽児円凜処剣剤剰労効勅勧勲単厳収唖営噛団" +
        "囲図圏園圧塁塩増壊壌壱売変奨嬢実富寛対専尭島巌巣巻帯帰并庁広廃弁" +
        "弐弾従徳徴応恵悩悪慎懐戦戯戻払抜択拝拠拡挙挿捜掲掻揺摂撃撹斉斎晃" +
        "晩暁暦曽栄桜桟検楽概様槙権欠歓歩歯歴殻毎気沢沪浄浜涙涼渇済渉渋渓" +
        "満溌滝瀬為焔焼犠猟獣瓶畳痩発県研砕砿稲穂穏穣竜粋粛糸経絵継続総緑" +
        "緒縁縄縦繊繋繍缶聴脳臓艶芸荘萌蔵薫薬蛍蝋衛覇覚覧観訳証読謡譲讃豊" +
        "賛転軽輌辺逓遅郎郷酔醗醤醸釈野鉄鉱銭鋳錬録鎮関闘陥険隠雑霊頴頼顕" +
        "顛餅駅駆騒験髄髪鴎鶏鹸麹麺黒黙齢"

    private const val KYUJITAI = "" +
        "兩竝乘龜豫亞佛假傳倂價儉僞兒圓凛處劍劑剩勞效敕勸勳單嚴收啞營嚙團" +
        "圍圖圈薗壓壘鹽增壞壤壹賣變獎孃實冨寬對專堯嶋巖巢卷帶歸幷廳廣廢辨" +
        "貳彈從德徵應惠惱惡愼懷戰戲戾拂拔擇拜據擴擧插搜揭搔搖攝擊攪齊齋晄" +
        "晚曉曆曾榮櫻棧檢樂槪樣槇權缺歡步齒歷殼每氣澤濾淨濱淚凉渴濟涉澁溪" +
        "滿潑瀧瀨爲焰燒犧獵獸甁疊瘦發縣硏碎礦稻穗穩穰龍粹肅絲經繪繼續總綠" +
        "緖緣繩縱纖繫繡罐聽腦臟艷藝莊萠藏薰藥螢蠟衞霸覺覽觀譯證讀謠讓讚豐" +
        "贊轉輕輛邊遞遲郞鄕醉醱醬釀釋埜鐵鑛錢鑄鍊錄鎭關鬪陷險隱雜靈穎賴顯" +
        "顚餠驛驅騷驗髓髮鷗鷄鹼麴麵黑默齡"

    /**
     * The kyujitai for [char], or [char] itself when it is not a shinjitai we know about.
     */
    fun toKyujitai(char: Char): Char {
        var low = 0
        var high = SHINJITAI.length - 1
        while (low <= high) {
            val mid = (low + high) ushr 1
            val candidate = SHINJITAI[mid]
            when {
                candidate < char -> low = mid + 1
                candidate > char -> high = mid - 1
                else -> return KYUJITAI[mid]
            }
        }
        return char
    }
}
