package eu.kanade.tachiyomi.data.local

import com.hippo.unifile.UniFile
import eu.kanade.tachiyomi.data.cache.CoverCache
import eu.kanade.tachiyomi.data.manga.MangaMark
import eu.kanade.tachiyomi.data.manga.MangaMarkStore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import logcat.LogPriority
import tachiyomi.core.common.util.system.logcat
import tachiyomi.domain.chapter.repository.ChapterRepository
import tachiyomi.domain.manga.repository.MangaRepository
import tachiyomi.domain.source.service.SourceManager
import tachiyomi.source.local.LocalSource
import tachiyomi.source.local.image.LocalChapterCoverManager
import tachiyomi.source.local.io.Archive
import tachiyomi.source.local.io.LocalSourceFileSystem
import uy.kohesive.injekt.Injekt
import uy.kohesive.injekt.api.get

/**
 * Deletes local manga files from disk and drops every trace of them from the database.
 *
 * A single service backs every delete entry point so the disk/database ordering stays
 * identical no matter where the action was triggered from.
 */
class LocalEntryDeletionService(
    private val fileSystem: LocalSourceFileSystem = Injekt.get(),
    private val mangaRepository: MangaRepository = Injekt.get(),
    private val chapterRepository: ChapterRepository = Injekt.get(),
    private val coverManager: LocalChapterCoverManager = Injekt.get(),
    private val coverCache: CoverCache = Injekt.get(),
    private val mangaMarkStore: MangaMarkStore = Injekt.get(),
    private val sourceManager: SourceManager = Injekt.get(),
) {

    private val mutex = Mutex()

    data class Result(
        val deleted: Int,
        val failed: List<String>,
    )

    /**
     * Deletes the local files of the given chapters.
     *
     * Once a manga loses its last chapter its directory is removed as well, so no empty shell is
     * left behind on disk. The directory is only taken when everything inside is either gone or
     * generated by the app itself (`cover.jpg` / `ComicInfo.xml` / `.nomedia`); anything the user
     * put there keeps the directory alive and is reported instead.
     *
     * Chapter urls are looked up here rather than passed in, so a caller can never hand over a
     * stale or empty path.
     */
    suspend fun deleteChapters(targets: List<ChapterTarget>): Result = withContext(Dispatchers.IO) {
        mutex.withLock {
            val base = fileSystem.getBaseDirectory()
            if (base == null) {
                logcat(LogPriority.ERROR) { "Local directory unavailable; nothing was deleted" }
                return@withLock Result(deleted = 0, failed = targets.map { it.name })
            }

            val resolved = runCatching {
                targets.groupBy { it.mangaId }.flatMap { (mangaId, group) ->
                    val wanted = group.associateBy { it.id }
                    chapterRepository.getChapterByMangaId(mangaId)
                        .filter { it.id in wanted }
                        .map { chapter -> wanted.getValue(chapter.id) to chapter }
                }
            }.onFailure {
                logcat(LogPriority.ERROR, it) { "Failed to resolve chapters before deletion" }
            }.getOrDefault(emptyList())

            val missing = targets.mapTo(mutableSetOf()) { it.id } -
                resolved.mapTo(mutableSetOf()) { it.first.id }
            val failed = mutableListOf<String>()
            targets.filter { it.id in missing }.forEach { failed += it.name }

            val deleted = mutableListOf<Pair<ChapterTarget, String>>()
            resolved.forEach { (target, chapter) ->
                runCatching {
                    // Re-resolve on every attempt: a concurrent move may have invalidated an
                    // earlier handle.
                    val file = resolveChapterFile(base, chapter.url)
                    if (file != null && deleteRecursively(file)) {
                        deleted += target to chapter.url
                    } else {
                        failed += target.name
                    }
                }.onFailure {
                    logcat(LogPriority.ERROR, it) { "Failed to delete ${target.name}" }
                    failed += target.name
                }
            }

            if (deleted.isNotEmpty()) {
                cleanupChapters(deleted.map { (target, url) -> target to url })
            }

            // Works that just lost their last chapter: drop the directory too so it disappears
            // from the library immediately instead of lingering until the next full refresh.
            deleted.map { (target, _) -> target.mangaId }.distinct().forEach { mangaId ->
                val dirName = resolved.firstOrNull { (target, _) -> target.mangaId == mangaId }
                    ?.second?.url?.substringBefore('/')
                when (dirName?.let { removeDirectoryIfEmptied(base, it) }) {
                    true -> cleanupEmptiedManga(mangaId)
                    false -> logcat(LogPriority.INFO) {
                        "Kept non-empty directory $dirName; it still holds unrelated files"
                    }
                    null -> Unit
                }
            }

            Result(deleted = deleted.size, failed = failed)
        }
    }

    /**
     * Deletes a whole manga directory. The database row is only dropped once every file in the
     * directory is gone, otherwise the leftover files would be re-indexed under a new identity
     * on the next scan and silently lose their history.
     */
    suspend fun deleteManga(manga: MangaEntry): Result = withContext(Dispatchers.IO) {
        mutex.withLock {
            val base = fileSystem.getBaseDirectory()
            if (base == null) {
                logcat(LogPriority.ERROR) { "Local directory unavailable; nothing was deleted" }
                return@withLock Result(deleted = 0, failed = listOf(manga.title))
            }

            val deleted = runCatching {
                val dir = base.findFile(manga.url)
                dir != null && deleteRecursively(dir)
            }.onFailure {
                logcat(LogPriority.ERROR, it) { "Failed to delete ${manga.title}" }
            }.getOrDefault(false)

            if (!deleted) {
                return@withLock Result(deleted = 0, failed = listOf(manga.title))
            }

            cleanupManga(manga)
            Result(deleted = 1, failed = emptyList())
        }
    }

    private suspend fun cleanupChapters(chapters: List<Pair<ChapterTarget, String>>) {
        runCatching {
            // Covers must go first: the generated name is derived from the file on disk.
            chapters.forEach { (target, url) -> coverManager.deleteChapterCovers(target.id, url) }
            // Marks are keyed by chapter id, so the timestamp is only carried to rebuild the
            // entry; the store drops whatever matches the id.
            val known = mangaMarkStore.marks.value.associateBy { it.chapterId }
            mangaMarkStore.setAll(
                chapters.map { (target, _) ->
                    MangaMark(
                        mangaId = target.mangaId,
                        mangaTitle = target.mangaTitle,
                        chapterId = target.id,
                        chapterName = target.name,
                        markedAt = known[target.id]?.markedAt ?: System.currentTimeMillis(),
                    )
                },
                false,
            )
            chapterRepository.removeChaptersWithIds(chapters.map { (target, _) -> target.id })
        }.onFailure {
            logcat(LogPriority.ERROR, it) { "Failed to clean up deleted chapters" }
        }
    }

    private suspend fun cleanupManga(manga: MangaEntry) {
        runCatching {
            coverCache.deleteFromCache(manga.manga, deleteCustomCover = true)
            mangaMarkStore.clearManga(manga.id)
            mangaRepository.deleteMangaById(manga.id)
            localSource()?.removeListingEntry(manga.url)
        }.onFailure {
            logcat(LogPriority.ERROR, it) { "Failed to clean up deleted manga" }
        }
    }

    /**
     * Deletes a manga directory that no longer holds a single chapter.
     *
     * Returns true when the directory is gone, false when it was kept because it still contains
     * something the app did not create, and null when there was nothing to decide.
     */
    private fun removeDirectoryIfEmptied(base: UniFile, dirName: String): Boolean? {
        val dir = base.findFile(dirName) ?: return null
        if (!dir.isDirectory) return null

        val leftover = dir.listFiles().orEmpty()
        if (leftover.any { isChapterFile(it) }) return false
        // Anything not generated by the app is the user's business; keep the directory.
        if (leftover.any { it.name !in GENERATED_FILE_NAMES }) {
            logcat(LogPriority.INFO) { "Directory $dirName holds unrelated files; keeping it" }
            return false
        }

        val removed = leftover.all { it.delete() } && dir.delete()
        if (!removed) {
            logcat(LogPriority.ERROR) { "Failed to remove emptied directory $dirName" }
        }
        return removed
    }

    /** Drops the database row of a manga whose directory was just removed. */
    private suspend fun cleanupEmptiedManga(mangaId: Long) {
        val manga = runCatching { mangaRepository.getMangaById(mangaId) }
            .onFailure { logcat(LogPriority.ERROR, it) { "Failed to load manga $mangaId" } }
            .getOrNull() ?: return
        cleanupManga(
            MangaEntry(
                id = manga.id,
                url = manga.url,
                title = manga.title,
                manga = manga,
            ),
        )
    }

    /** Mirrors how the local source itself recognises a chapter, so both agree on what counts. */
    private fun isChapterFile(file: UniFile): Boolean {
        val name = file.name.orEmpty()
        return !name.startsWith('.') &&
            (file.isDirectory || Archive.isSupported(file) || name.endsWith(".epub", ignoreCase = true))
    }

    private fun resolveChapterFile(base: UniFile, chapterUrl: String): UniFile? {
        val parts = chapterUrl.split('/', limit = 2)
        if (parts.size < 2) return null
        return base.findFile(parts[0])?.findFile(parts[1])
    }

    private fun localSource(): LocalSource? =
        sourceManager.get(LocalSource.ID) as? LocalSource

    private fun deleteRecursively(file: UniFile): Boolean {
        if (file.isDirectory) {
            val children = file.listFiles().orEmpty()
            if (children.any { !deleteRecursively(it) }) return false
        }
        return file.delete()
    }

    /** A chapter picked for deletion. The file path is resolved by the service, not by the caller. */
    data class ChapterTarget(
        val id: Long,
        val mangaId: Long,
        val mangaTitle: String,
        val name: String,
    )

    data class MangaEntry(
        val id: Long,
        val url: String,
        val title: String,
        val manga: tachiyomi.domain.manga.model.Manga,
    )

    companion object {
        /**
         * Files the app itself writes next to the chapters. A directory holding only these counts
         * as empty once its chapters are gone and may be removed.
         */
        private val GENERATED_FILE_NAMES = setOf("cover.jpg", "ComicInfo.xml", ".nomedia")
    }
}
